[AdminType]
type = "enum"
storage = "string"
variants = ["Developer", "SuperAdmin", "Admin"]

auth = true
auth_model = "admin"

[model.admin]
table = "admin"
pk = "id"
pk_type = "i64"
id_strategy = "snowflake"
soft_delete = true
fields = [
  "id:i64",
  "username:string",
  "email:Option<String>",
  "locale:Option<String>",
  "password:hashed",
  "name:string",
  "admin_type:AdminType",
  "abilities:serde_json::Value",
  "created_at:datetime",
  "updated_at:datetime"
]

[model.http_client_log]
table = "http_client_logs"
pk = "id"
pk_type = "uuid"
disable_timestamps = true
fields = [
  "request_url:string",
  "request_method:string",
  "response_status:i32",
  "duration_ms:i32",
  "request_headers:serde_json::Value",
  "request_body:Option<String>",
  "response_headers:serde_json::Value",
  "response_body:Option<String>",
  "created_at:datetime"
]

[model.webhook_log]
table = "webhook_logs"
pk = "id"
pk_type = "uuid"
disable_timestamps = true
fields = [
  "request_url:string",
  "request_method:string",
  "response_status:i32",
  "duration_ms:i32",
  "request_headers:serde_json::Value",
  "request_body:Option<String>",
  "response_body:Option<String>",
  "created_at:datetime"
]
