[ContentPageSystemFlag]
type = "enum"
storage = "i16"
variants = [
  { name = "No", value = 0 },
  { name = "Yes", value = 1 }
]

[model.content_page]
table = "content_pages"
pk = "id"
pk_type = "i64"
id_strategy = "snowflake"
soft_delete = true
localized = ["title", "content", "cover"]
fields = [
  "id:i64",
  "tag:string",
  "is_system:ContentPageSystemFlag",
  "created_at:datetime",
  "updated_at:datetime"
]
