// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

export type AdminType = "developer" | "superadmin" | "admin";

export const ADMIN_TYPE: Readonly<Record<string, AdminType>> = {
  DEVELOPER: "developer",
  SUPERADMIN: "superadmin",
  ADMIN: "admin",
};

export const ADMIN_TYPES: ReadonlyArray<AdminType> = [
  "developer",
  "superadmin",
  "admin",
];

export type AuthClientType = "web" | "mobile";

export type ContentPageSystemFlag = "0" | "1";

export const CONTENT_PAGE_SYSTEM_FLAG: Readonly<Record<string, ContentPageSystemFlag>> = {
  _0: "0",
  _1: "1",
};

export const CONTENT_PAGE_SYSTEM_FLAGS: ReadonlyArray<ContentPageSystemFlag> = [
  "0",
  "1",
];

export type Permission = "admin.read" | "admin.manage" | "content_page.read" | "content_page.manage" | "country.read" | "country.manage" | "export";

export interface PermissionMeta {
  key: Permission;
  guard: string;
  label: string;
  group: string;
  description: string;
}

export const PERMISSION_META: ReadonlyArray<PermissionMeta> = [
  { key: "admin.read", guard: "admin", label: "Read Admins", group: "admin", description: "View admin profile and datatable records." },
  { key: "admin.manage", guard: "admin", label: "Manage Admins", group: "admin", description: "Create/update/delete admin records and perform management actions." },
  { key: "content_page.read", guard: "admin", label: "Read Content Pages", group: "content_page", description: "View policy pages and content-page datatable records." },
  { key: "content_page.manage", guard: "admin", label: "Manage Content Pages", group: "content_page", description: "Update and delete non-system pages." },
  { key: "country.read", guard: "admin", label: "Read Countries", group: "country", description: "View countries and country datatable records." },
  { key: "country.manage", guard: "admin", label: "Manage Countries", group: "country", description: "Update country status." },
  { key: "export", guard: "admin", label: "Export Data", group: "datatable", description: "Export datatable records as CSV." },
];

export const PERMISSIONS: ReadonlyArray<Permission> = [
  "admin.read",
  "admin.manage",
  "content_page.read",
  "content_page.manage",
  "country.read",
  "country.manage",
  "export",
];

export const PERMISSION: Readonly<Record<string, Permission>> = {
  ADMIN_READ: "admin.read",
  ADMIN_MANAGE: "admin.manage",
  CONTENT_PAGE_READ: "content_page.read",
  CONTENT_PAGE_MANAGE: "content_page.manage",
  COUNTRY_READ: "country.read",
  COUNTRY_MANAGE: "country.manage",
  EXPORT: "export",
};

export const PERMISSION_META_BY_KEY: Readonly<Record<Permission, PermissionMeta>> = {
  "admin.read": { key: "admin.read", guard: "admin", label: "Read Admins", group: "admin", description: "View admin profile and datatable records." },
  "admin.manage": { key: "admin.manage", guard: "admin", label: "Manage Admins", group: "admin", description: "Create/update/delete admin records and perform management actions." },
  "content_page.read": { key: "content_page.read", guard: "admin", label: "Read Content Pages", group: "content_page", description: "View policy pages and content-page datatable records." },
  "content_page.manage": { key: "content_page.manage", guard: "admin", label: "Manage Content Pages", group: "content_page", description: "Update and delete non-system pages." },
  "country.read": { key: "country.read", guard: "admin", label: "Read Countries", group: "country", description: "View countries and country datatable records." },
  "country.manage": { key: "country.manage", guard: "admin", label: "Manage Countries", group: "country", description: "Update country status." },
  "export": { key: "export", guard: "admin", label: "Export Data", group: "datatable", description: "Export datatable records as CSV." },
};
