// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

export type AdjustableCreditType = "1";

export const ADJUSTABLE_CREDIT_TYPE: Readonly<Record<string, AdjustableCreditType>> = {
  _1: "1",
};

export const ADJUSTABLE_CREDIT_TYPES: ReadonlyArray<AdjustableCreditType> = [
  "1",
];

export type AdminType = "developer" | "superadmin" | "admin";

export const ADMIN_TYPE: Readonly<Record<string, AdminType>> = {
  DEVELOPER: "developer",
  SUPERADMIN: "superadmin",
  ADMIN: "admin",
};

export const ADMIN_TYPES: ReadonlyArray<AdminType> = [
  "developer",
  "superadmin",
  "admin",
];

export type AuditAction = "1" | "2" | "3";

export const AUDIT_ACTION: Readonly<Record<string, AuditAction>> = {
  _1: "1",
  _2: "2",
  _3: "3",
};

export const AUDIT_ACTIONS: ReadonlyArray<AuditAction> = [
  "1",
  "2",
  "3",
];

export type AuthClientType = "web" | "mobile";

export type BankStatus = "1" | "2";

export const BANK_STATUS: Readonly<Record<string, BankStatus>> = {
  _1: "1",
  _2: "2",
};

export const BANK_STATUSES: ReadonlyArray<BankStatus> = [
  "1",
  "2",
];

export type CompanyBankAccountStatus = "1" | "2";

export const COMPANY_BANK_ACCOUNT_STATUS: Readonly<Record<string, CompanyBankAccountStatus>> = {
  _1: "1",
  _2: "2",
};

export const COMPANY_BANK_ACCOUNT_STATUSES: ReadonlyArray<CompanyBankAccountStatus> = [
  "1",
  "2",
];

export type CompanyCryptoAccountStatus = "1" | "2";

export const COMPANY_CRYPTO_ACCOUNT_STATUS: Readonly<Record<string, CompanyCryptoAccountStatus>> = {
  _1: "1",
  _2: "2",
};

export const COMPANY_CRYPTO_ACCOUNT_STATUSES: ReadonlyArray<CompanyCryptoAccountStatus> = [
  "1",
  "2",
];

export type ContentPageSystemFlag = "0" | "1";

export const CONTENT_PAGE_SYSTEM_FLAG: Readonly<Record<string, ContentPageSystemFlag>> = {
  _0: "0",
  _1: "1",
};

export const CONTENT_PAGE_SYSTEM_FLAGS: ReadonlyArray<ContentPageSystemFlag> = [
  "0",
  "1",
];

export type CreditTransactionType = "101" | "102" | "201" | "202" | "301" | "302" | "401";

export const CREDIT_TRANSACTION_TYPE: Readonly<Record<string, CreditTransactionType>> = {
  _101: "101",
  _102: "102",
  _201: "201",
  _202: "202",
  _301: "301",
  _302: "302",
  _401: "401",
};

export const CREDIT_TRANSACTION_TYPES: ReadonlyArray<CreditTransactionType> = [
  "101",
  "102",
  "201",
  "202",
  "301",
  "302",
  "401",
];

export type CreditType = "1" | "2";

export const CREDIT_TYPE: Readonly<Record<string, CreditType>> = {
  _1: "1",
  _2: "2",
};

export const CREDIT_TYPES: ReadonlyArray<CreditType> = [
  "1",
  "2",
];

export type CryptoNetworkStatus = "1" | "2";

export const CRYPTO_NETWORK_STATUS: Readonly<Record<string, CryptoNetworkStatus>> = {
  _1: "1",
  _2: "2",
};

export const CRYPTO_NETWORK_STATUSES: ReadonlyArray<CryptoNetworkStatus> = [
  "1",
  "2",
];

export type DepositMethod = "1";

export const DEPOSIT_METHOD: Readonly<Record<string, DepositMethod>> = {
  _1: "1",
};

export const DEPOSIT_METHODS: ReadonlyArray<DepositMethod> = [
  "1",
];

export type DepositReviewAction = "1" | "2";

export const DEPOSIT_REVIEW_ACTION: Readonly<Record<string, DepositReviewAction>> = {
  _1: "1",
  _2: "2",
};

export const DEPOSIT_REVIEW_ACTIONS: ReadonlyArray<DepositReviewAction> = [
  "1",
  "2",
];

export type DepositStatus = "1" | "2" | "3";

export const DEPOSIT_STATUS: Readonly<Record<string, DepositStatus>> = {
  _1: "1",
  _2: "2",
  _3: "3",
};

export const DEPOSIT_STATUSES: ReadonlyArray<DepositStatus> = [
  "1",
  "2",
  "3",
];

export type OwnerType = "1";

export const OWNER_TYPE: Readonly<Record<string, OwnerType>> = {
  _1: "1",
};

export const OWNER_TYPES: ReadonlyArray<OwnerType> = [
  "1",
];

export type Permission = "admin.read" | "admin.manage" | "content_page.read" | "content_page.manage" | "country.read" | "country.manage" | "user.read" | "user.manage" | "user.hierarchy" | "user.change_introducer" | "user.credit_read" | "user.credit_manage" | "audit_log.read" | "deposit.read" | "deposit.manage" | "withdrawal.read" | "withdrawal.manage" | "bank.read" | "bank.manage" | "crypto_network.read" | "crypto_network.manage" | "company_bank_account.read" | "company_bank_account.manage" | "company_crypto_account.read" | "company_crypto_account.manage" | "export";

export interface PermissionMeta {
  key: Permission;
  guard: string;
  label: string;
  group: string;
  description: string;
}

export const PERMISSION_META: ReadonlyArray<PermissionMeta> = [
  { key: "admin.read", guard: "admin", label: "Read Admins", group: "admin", description: "View admin profile and datatable records." },
  { key: "admin.manage", guard: "admin", label: "Manage Admins", group: "admin", description: "Create/update/delete admin records and perform management actions." },
  { key: "content_page.read", guard: "admin", label: "Read Content Pages", group: "content_page", description: "View policy pages and content-page datatable records." },
  { key: "content_page.manage", guard: "admin", label: "Manage Content Pages", group: "content_page", description: "Update and delete non-system pages." },
  { key: "country.read", guard: "admin", label: "Read Countries", group: "country", description: "View countries and country datatable records." },
  { key: "country.manage", guard: "admin", label: "Manage Countries", group: "country", description: "Update country status." },
  { key: "user.read", guard: "admin", label: "Read Users", group: "user", description: "View user profiles and datatable records." },
  { key: "user.manage", guard: "admin", label: "Manage Users", group: "user", description: "Create/update/ban/unban user records." },
  { key: "user.hierarchy", guard: "admin", label: "View User Hierarchy", group: "user", description: "Browse user referral tree and navigate downlines." },
  { key: "user.change_introducer", guard: "admin", label: "Change User Introducer", group: "user", description: "Change a user's introducer and view change logs." },
  { key: "user.credit_read", guard: "admin", label: "Read User Credits", group: "user", description: "View credit transactions and balances." },
  { key: "user.credit_manage", guard: "admin", label: "Manage User Credits", group: "user", description: "Adjust user credit balances." },
  { key: "audit_log.read", guard: "admin", label: "Read Audit Logs", group: "audit_log", description: "View audit log datatable and inspect change details." },
  { key: "deposit.read", guard: "admin", label: "Read Deposits", group: "finance", description: "View deposit records." },
  { key: "deposit.manage", guard: "admin", label: "Manage Deposits", group: "finance", description: "Approve or reject deposit requests." },
  { key: "withdrawal.read", guard: "admin", label: "Read Withdrawals", group: "finance", description: "View withdrawal records." },
  { key: "withdrawal.manage", guard: "admin", label: "Manage Withdrawals", group: "finance", description: "Process, approve or reject withdrawal requests." },
  { key: "bank.read", guard: "admin", label: "Read Banks", group: "finance", description: "View bank list." },
  { key: "bank.manage", guard: "admin", label: "Manage Banks", group: "finance", description: "Create, update, delete banks." },
  { key: "crypto_network.read", guard: "admin", label: "Read Crypto Networks", group: "finance", description: "View crypto network list." },
  { key: "crypto_network.manage", guard: "admin", label: "Manage Crypto Networks", group: "finance", description: "Create, update, delete crypto networks." },
  { key: "company_bank_account.read", guard: "admin", label: "Read Company Bank Accounts", group: "finance", description: "View company bank accounts." },
  { key: "company_bank_account.manage", guard: "admin", label: "Manage Company Bank Accounts", group: "finance", description: "Create, update, delete company bank accounts." },
  { key: "company_crypto_account.read", guard: "admin", label: "Read Company Crypto Accounts", group: "finance", description: "View company crypto accounts." },
  { key: "company_crypto_account.manage", guard: "admin", label: "Manage Company Crypto Accounts", group: "finance", description: "Create, update, delete company crypto accounts." },
  { key: "export", guard: "admin", label: "Export Data", group: "datatable", description: "Export datatable records as CSV." },
];

export const PERMISSIONS: ReadonlyArray<Permission> = [
  "admin.read",
  "admin.manage",
  "content_page.read",
  "content_page.manage",
  "country.read",
  "country.manage",
  "user.read",
  "user.manage",
  "user.hierarchy",
  "user.change_introducer",
  "user.credit_read",
  "user.credit_manage",
  "audit_log.read",
  "deposit.read",
  "deposit.manage",
  "withdrawal.read",
  "withdrawal.manage",
  "bank.read",
  "bank.manage",
  "crypto_network.read",
  "crypto_network.manage",
  "company_bank_account.read",
  "company_bank_account.manage",
  "company_crypto_account.read",
  "company_crypto_account.manage",
  "export",
];

export const PERMISSION: Readonly<Record<string, Permission>> = {
  ADMIN_READ: "admin.read",
  ADMIN_MANAGE: "admin.manage",
  CONTENT_PAGE_READ: "content_page.read",
  CONTENT_PAGE_MANAGE: "content_page.manage",
  COUNTRY_READ: "country.read",
  COUNTRY_MANAGE: "country.manage",
  USER_READ: "user.read",
  USER_MANAGE: "user.manage",
  USER_HIERARCHY: "user.hierarchy",
  USER_CHANGE_INTRODUCER: "user.change_introducer",
  USER_CREDIT_READ: "user.credit_read",
  USER_CREDIT_MANAGE: "user.credit_manage",
  AUDIT_LOG_READ: "audit_log.read",
  DEPOSIT_READ: "deposit.read",
  DEPOSIT_MANAGE: "deposit.manage",
  WITHDRAWAL_READ: "withdrawal.read",
  WITHDRAWAL_MANAGE: "withdrawal.manage",
  BANK_READ: "bank.read",
  BANK_MANAGE: "bank.manage",
  CRYPTO_NETWORK_READ: "crypto_network.read",
  CRYPTO_NETWORK_MANAGE: "crypto_network.manage",
  COMPANY_BANK_ACCOUNT_READ: "company_bank_account.read",
  COMPANY_BANK_ACCOUNT_MANAGE: "company_bank_account.manage",
  COMPANY_CRYPTO_ACCOUNT_READ: "company_crypto_account.read",
  COMPANY_CRYPTO_ACCOUNT_MANAGE: "company_crypto_account.manage",
  EXPORT: "export",
};

export const PERMISSION_META_BY_KEY: Readonly<Record<Permission, PermissionMeta>> = {
  "admin.read": { key: "admin.read", guard: "admin", label: "Read Admins", group: "admin", description: "View admin profile and datatable records." },
  "admin.manage": { key: "admin.manage", guard: "admin", label: "Manage Admins", group: "admin", description: "Create/update/delete admin records and perform management actions." },
  "content_page.read": { key: "content_page.read", guard: "admin", label: "Read Content Pages", group: "content_page", description: "View policy pages and content-page datatable records." },
  "content_page.manage": { key: "content_page.manage", guard: "admin", label: "Manage Content Pages", group: "content_page", description: "Update and delete non-system pages." },
  "country.read": { key: "country.read", guard: "admin", label: "Read Countries", group: "country", description: "View countries and country datatable records." },
  "country.manage": { key: "country.manage", guard: "admin", label: "Manage Countries", group: "country", description: "Update country status." },
  "user.read": { key: "user.read", guard: "admin", label: "Read Users", group: "user", description: "View user profiles and datatable records." },
  "user.manage": { key: "user.manage", guard: "admin", label: "Manage Users", group: "user", description: "Create/update/ban/unban user records." },
  "user.hierarchy": { key: "user.hierarchy", guard: "admin", label: "View User Hierarchy", group: "user", description: "Browse user referral tree and navigate downlines." },
  "user.change_introducer": { key: "user.change_introducer", guard: "admin", label: "Change User Introducer", group: "user", description: "Change a user's introducer and view change logs." },
  "user.credit_read": { key: "user.credit_read", guard: "admin", label: "Read User Credits", group: "user", description: "View credit transactions and balances." },
  "user.credit_manage": { key: "user.credit_manage", guard: "admin", label: "Manage User Credits", group: "user", description: "Adjust user credit balances." },
  "audit_log.read": { key: "audit_log.read", guard: "admin", label: "Read Audit Logs", group: "audit_log", description: "View audit log datatable and inspect change details." },
  "deposit.read": { key: "deposit.read", guard: "admin", label: "Read Deposits", group: "finance", description: "View deposit records." },
  "deposit.manage": { key: "deposit.manage", guard: "admin", label: "Manage Deposits", group: "finance", description: "Approve or reject deposit requests." },
  "withdrawal.read": { key: "withdrawal.read", guard: "admin", label: "Read Withdrawals", group: "finance", description: "View withdrawal records." },
  "withdrawal.manage": { key: "withdrawal.manage", guard: "admin", label: "Manage Withdrawals", group: "finance", description: "Process, approve or reject withdrawal requests." },
  "bank.read": { key: "bank.read", guard: "admin", label: "Read Banks", group: "finance", description: "View bank list." },
  "bank.manage": { key: "bank.manage", guard: "admin", label: "Manage Banks", group: "finance", description: "Create, update, delete banks." },
  "crypto_network.read": { key: "crypto_network.read", guard: "admin", label: "Read Crypto Networks", group: "finance", description: "View crypto network list." },
  "crypto_network.manage": { key: "crypto_network.manage", guard: "admin", label: "Manage Crypto Networks", group: "finance", description: "Create, update, delete crypto networks." },
  "company_bank_account.read": { key: "company_bank_account.read", guard: "admin", label: "Read Company Bank Accounts", group: "finance", description: "View company bank accounts." },
  "company_bank_account.manage": { key: "company_bank_account.manage", guard: "admin", label: "Manage Company Bank Accounts", group: "finance", description: "Create, update, delete company bank accounts." },
  "company_crypto_account.read": { key: "company_crypto_account.read", guard: "admin", label: "Read Company Crypto Accounts", group: "finance", description: "View company crypto accounts." },
  "company_crypto_account.manage": { key: "company_crypto_account.manage", guard: "admin", label: "Manage Company Crypto Accounts", group: "finance", description: "Create, update, delete company crypto accounts." },
  "export": { key: "export", guard: "admin", label: "Export Data", group: "datatable", description: "Export datatable records as CSV." },
};

export type UserBanStatus = "0" | "1";

export const USER_BAN_STATUS: Readonly<Record<string, UserBanStatus>> = {
  _0: "0",
  _1: "1",
};

export const USER_BAN_STATUSES: ReadonlyArray<UserBanStatus> = [
  "0",
  "1",
];

export type WithdrawalMethod = "1";

export const WITHDRAWAL_METHOD: Readonly<Record<string, WithdrawalMethod>> = {
  _1: "1",
};

export const WITHDRAWAL_METHODS: ReadonlyArray<WithdrawalMethod> = [
  "1",
];

export type WithdrawalReviewAction = "1" | "2" | "3";

export const WITHDRAWAL_REVIEW_ACTION: Readonly<Record<string, WithdrawalReviewAction>> = {
  _1: "1",
  _2: "2",
  _3: "3",
};

export const WITHDRAWAL_REVIEW_ACTIONS: ReadonlyArray<WithdrawalReviewAction> = [
  "1",
  "2",
  "3",
];

export type WithdrawalStatus = "1" | "2" | "3" | "4";

export const WITHDRAWAL_STATUS: Readonly<Record<string, WithdrawalStatus>> = {
  _1: "1",
  _2: "2",
  _3: "3",
  _4: "4",
};

export const WITHDRAWAL_STATUSES: ReadonlyArray<WithdrawalStatus> = [
  "1",
  "2",
  "3",
  "4",
];
