[model.attachment]
table = "attachments"
pk = "id"
pk_type = "uuid"
id_strategy = "manual"
soft_delete = true
fields = [
  "id:uuid",
  "owner_type:String",
  "owner_id:i64",
  "field:String",
  "path:String",
  "content_type:String",
  "size:i64",
  "width:Option<i32>",
  "height:Option<i32>",
  "created_at:datetime",
  "updated_at:datetime"
]
disable_timestamps = true
