[model.failed_job]
table = "failed_jobs"
pk = "id"
pk_type = "uuid"
id_strategy = "manual"
disable_timestamps = true
fields = [
  "id:uuid",
  "job_name:String",
  "queue:String",
  "payload:serde_json::Value",
  "error:String",
  "attempts:i32",
  "group_id:Option<String>",
  "failed_at:datetime"
]

[model.outbox_job]
table = "outbox_jobs"
pk = "id"
pk_type = "uuid"
id_strategy = "manual"
disable_timestamps = true
fields = [
  "id:uuid",
  "queue:String",
  "payload:serde_json::Value",
  "created_at:datetime"
]
