[model.localized]
table = "localized"
pk = "id"
pk_type = "i64"
id_strategy = "manual"
disable_timestamps = true
fields = [
  "id:i64",
  "owner_type:String",
  "owner_id:i64",
  "field:String",
  "locale:String",
  "value:String"
]
