// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownlineNode = { id: string, uuid: string, username: string, name: string | null, downline_count: number, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownlinesOutput = { parent_username: string, parent_name: string | null, downlines: Array<{ id: string, uuid: string, username: string, name: string | null, downline_count: number, }>, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownlinesQuery = { parent_user_id: string | null, };

