// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AuthClientType } from "@user/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolveReferralOutput = { username: string, name: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolveReferralQuery = { code: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAuthOutput = { token_type: string, access_token: string, access_expires_at: string | null, refresh_token: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserLocaleUpdateInput = { locale: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserLocaleUpdateOutput = { locale: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserLoginInput = { username: string, password: string, client_type: AuthClientType, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserLogoutInput = { client_type: AuthClientType, refresh_token: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserLogoutOutput = { revoked: boolean, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserMeOutput = { id: string, uuid: string, username: string, name: string, email: string | null, locale: string | null, country_iso2: string | null, contact_number: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPasswordUpdateInput = { current_password: string, password: string, password_confirmation: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPasswordUpdateOutput = { updated: boolean, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfileUpdateInput = { name: string | null, email: string | null, country_iso2: string | null, contact_number: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfileUpdateOutput = { id: string, username: string, name: string, email: string | null, locale: string | null, country_iso2: string | null, contact_number: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserRefreshInput = { client_type: AuthClientType, refresh_token: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserRegisterInput = { username: string, password: string, password_confirmation: string, name: string | null, email: string | null, country_iso2: string | null, contact_number: string | null, referral_code: string | null, client_type: AuthClientType, };

