// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AdminType, Permission } from "./enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAdminInput = { username: string, email: string | null, name: string, admin_type: AdminType, password: string, abilities: Permission[], };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAdminInput = { username: string | null, email: string | null, name: string | null, admin_type: AdminType | null, abilities: Permission[] | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminOutput = { id: bigint, username: string, email: string | null, name: string, admin_type: AdminType, abilities: Array<string>, created_at: string, updated_at: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDeleteOutput = { deleted: boolean, };

