// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CreditType, OwnerType, WithdrawalMethod, WithdrawalReviewAction, WithdrawalStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminWithdrawalReviewInput = { action: WithdrawalReviewAction, admin_remark: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WithdrawalOutput = { id: string, owner_type: OwnerType, owner_id: string, credit_type: CreditType, withdrawal_method: WithdrawalMethod, bank_id: string | null, bank_account_name: string | null, bank_account_number: string | null, crypto_network_id: string | null, crypto_wallet_address: string | null, conversion_rate: string | null, status: WithdrawalStatus, amount: string, fee: string, net_amount: string, related_key: string | null, remark: string | null, admin_remark: string | null, reviewed_at: string | null, created_at: string, };
