// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CompanyCryptoAccountStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminCompanyCryptoAccountInput = { crypto_network_id: string, wallet_address: string, conversion_rate: string, status: CompanyCryptoAccountStatus, sort_order: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompanyCryptoAccountOutput = { id: string, crypto_network_id: string, crypto_network_name: string | null, wallet_address: string, conversion_rate: string, status: CompanyCryptoAccountStatus, sort_order: number, created_at: string, updated_at: string, };
