// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CreditType, DepositMethod, DepositReviewAction, DepositStatus, OwnerType } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDepositReviewInput = { action: DepositReviewAction, admin_remark: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DepositOutput = { id: string, owner_type: OwnerType, owner_id: string, credit_type: CreditType, deposit_method: DepositMethod, company_bank_account_id: string | null, company_crypto_account_id: string | null, conversion_rate: string | null, status: DepositStatus, amount: string, fee: string, net_amount: string, related_key: string | null, remark: string | null, admin_remark: string | null, reviewed_at: string | null, created_at: string, };
