// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AdminType, AuthClientType } from "./enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminLoginInput = { username: string, password: string, client_type: AuthClientType, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminRefreshInput = { client_type: AuthClientType, refresh_token: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminLogoutInput = { client_type: AuthClientType, refresh_token: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminProfileUpdateInput = { name: string, email: string | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPasswordUpdateInput = { current_password: string, password: string, password_confirmation: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminAuthOutput = { token_type: string, access_token: string, access_expires_at: string | null, refresh_token: string | null, scopes: Array<string>, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMeOutput = { id: bigint, username: string, email: string | null, name: string, admin_type: AdminType, scopes: Array<string>, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminProfileUpdateOutput = { id: bigint, username: string, email: string | null, name: string, admin_type: AdminType, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPasswordUpdateOutput = { updated: boolean, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminLogoutOutput = { revoked: boolean, };

