// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminTiptapImageUploadOutput = { folder: string, path: string, url: string, content_type: string, size: number, width: number | null, height: number | null, };

