// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AdminType, Permission } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDeleteOutput = { deleted: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminOutput = { id: string, identity: string, username: string, email: string | null, name: string, admin_type: AdminType, abilities: Array<Permission>, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAdminInput = { username: string, email: string | null, name: string, password: string, abilities: Array<Permission>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAdminInput = { id: string, username: string | null, email: string | null, name: string | null, password: string | null, abilities: Array<Permission> | null, };
