// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CryptoNetworkStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminCryptoNetworkInput = { name: string, symbol: string, status: CryptoNetworkStatus, sort_order: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CryptoNetworkOutput = { id: string, name: string, symbol: string, logo_url: string | null, status: CryptoNetworkStatus, sort_order: number, created_at: string, updated_at: string, };
