// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { LocalizedInput } from "@shared/types/platform";
import type { AdjustableCreditType, CreditTransactionType, CreditType } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminCreditAdjustInput = { username: string, credit_type: AdjustableCreditType, amount: string, remark: string | null, 
/**
 * Enable custom description
 */
custom_description: boolean, 
/**
 * Localized custom description text (required when custom_description is true)
 */
custom_description_text: LocalizedInput | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserCreditTransactionOutput = { id: string, user_id: string, credit_type: CreditType, amount: string, transaction_type: CreditTransactionType, related_key: string | null, remark: string | null, created_at: string, };

