// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDownlineNode = { id: string, uuid: string, username: string, name: string | null, downline_count: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDownlinesOutput = { parent_id: string, parent_username: string, parent_name: string | null, parent_introducer_user_id: string | null, downlines: Array<{ id: string, uuid: string, username: string, name: string | null, downline_count: number, }>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolvedUser = { id: string, username: string, name: string | null, introducer_user_id: string | null, };
