// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { ContentPageSystemFlag } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminContentPageDeleteOutput = { deleted: boolean, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminContentPageOutput = { id: string, tag: string, is_system: ContentPageSystemFlag, title: LocalizedText, content: LocalizedText, cover: LocalizedText, cover_url: LocalizedText, created_at: string, updated_at: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminContentPageUpdateInput = { tag: string, title: LocalizedText, content: LocalizedText, cover: LocalizedText, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminContentPageUpdateOutput = { id: string, tag: string, is_system: ContentPageSystemFlag, title: LocalizedText, content: LocalizedText, cover: LocalizedText, cover_url: LocalizedText, created_at: string, updated_at: string, };

