// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CompanyBankAccountStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminCompanyBankAccountInput = { bank_id: string, account_name: string, account_number: string, status: CompanyBankAccountStatus, sort_order: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompanyBankAccountOutput = { id: string, bank_id: string, bank_name: string | null, account_name: string, account_number: string, status: CompanyBankAccountStatus, sort_order: number, created_at: string, updated_at: string, };
