// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { UserBanStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchResolveEntry = { id: string, username: string, name: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchResolveOutput = { entries: Array<{ id: string, username: string, name: string | null, }>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateUserInput = { username: string, email: string | null, name: string | null, password: string, country_iso2: string | null, contact_number: string | null, introducer_username: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateUserInput = { id: string, username: string | null, email: string | null, name: string | null, password: string | null, country_iso2: string | null, contact_number: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserBanInput = { ban: UserBanStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserBanOutput = { banned: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserManageOutput = { id: string, uuid: string, username: string, name: string | null, email: string | null, locale: string | null, country_iso2: string | null, contact_number: string | null, ban: UserBanStatus, created_at: string, updated_at: string, };
