// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AdminType } from "./enums";
import type { DataTableQueryRequestBase, DataTableEmailExportRequestBase } from "../../shared/types/datatable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDatatableQueryInput = { base: DataTableQueryRequestBase, q: string | null, username: string | null, email: string | null, admin_type: AdminType | null, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDatatableEmailExportInput = { base: DataTableEmailExportRequestBase, q: string | null, username: string | null, email: string | null, admin_type: AdminType | null, };

