// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountryDatatableRow = { id: string, iso2: string, iso3: string, name: string, region: string | null, calling_code: string | null, status: string, is_default: boolean, updated_at: string, };

