// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CryptoNetworkStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CryptoNetworkDatatableRow = { id: string, name: string, symbol: string, status: CryptoNetworkStatus, status_label: string, sort_order: number, updated_at: string, };
