// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CompanyCryptoAccountStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompanyCryptoAccountDatatableRow = { id: string, crypto_network_id: string, crypto_network_name: string | null, wallet_address: string, conversion_rate: string, status: CompanyCryptoAccountStatus, status_label: string, sort_order: number, updated_at: string, };
