// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AdminType } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDatatableRow = { id: string, identity: string, username: string, email: string | null, name: string, admin_type: AdminType, abilities: Array<string>, created_at: string, updated_at: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDatatableSummaryOutput = { total_admin_counts: number, total_filtered: number, developer_count: number, superadmin_count: number, admin_count: number, };

