// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { UserBanStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserDatatableRow = { id: string, uuid: string, username: string, name: string | null, email: string | null, locale: string | null, country_iso2: string | null, contact_number: string | null, ban: UserBanStatus, credit_1: string, credit_2: string, introducer_user_id: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserDatatableSummaryOutput = { total_user_count: number, total_filtered: number, banned_count: number, total_credit_1: string, total_credit_2: string, };
