// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { AuditAction } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditLogDatatableRow = { id: string, admin_id: string, admin_username: string, action: AuditAction, action_explained: string, table_name: string, record_key: string, old_data: Record<string, unknown> | null, new_data: Record<string, unknown> | null, created_at: string, };
