// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { ContentPageSystemFlag } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentPageDatatableRow = { id: string, tag: string, title: string | null, is_system: ContentPageSystemFlag, updated_at: string, };

