// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpClientLogDatatableRow = { id: string, request_url: string, request_method: string, response_status: number | null, duration_ms: number | null, request_headers: Record<string, unknown> | null, request_body: string | null, response_headers: Record<string, unknown> | null, response_body: string | null, created_at: string, };

