// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SqlProfilerQueryDatatableRow = { id: string, request_id: string, table_name: string, operation: string, sql: string, binds: string, duration_us: bigint, created_at: string, };
