// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CreditTransactionType, CreditType } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserCreditTransactionDatatableRow = { id: string, user_id: string, admin_id: string | null, credit_type: CreditType, amount: string, transaction_type: CreditTransactionType, 
/**
 * Backend-computed human-readable label for the transaction type,
 * respecting current locale and interpolating dynamic `params`.
 * If `remark` is set, it overrides this value.
 */
transaction_type_explained: string, related_key: string | null, remark: string | null, user_username: string | null, admin_username: string | null, custom_description: boolean, created_at: string, updated_at: string, };
