// Auto-generated by `cargo run -p app --bin export-types`.
// Do not edit manually — run `make gen-types` to regenerate.
import type { CreditType, OwnerType, WithdrawalMethod, WithdrawalStatus } from "@admin/types/enums";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WithdrawalDatatableRow = { id: string, owner_type: OwnerType, owner_id: string, admin_id: string | null, credit_type: CreditType, withdrawal_method: WithdrawalMethod, bank_id: string | null, bank_name: string | null, crypto_network_id: string | null, crypto_network_name: string | null, conversion_rate: string | null, status: WithdrawalStatus, status_label: string, amount: string, fee: string, net_amount: string, related_key: string | null, remark: string | null, admin_remark: string | null, owner_name: string | null, admin_username: string | null, reviewed_at: string | null, created_at: string, updated_at: string, };
